<?php if ( ! defined( 'ABSPATH' ) ) { exit; } $week_start = new DateTime(); $week_start->setISODate( (int) gmdate( 'o', $timestamp ), (int) gmdate( 'W', $timestamp ) ); ?>
<div class="wrap rr-admin-wrap">
	<h1><?php esc_html_e( 'Reservation Statistics', 'restaurant-reservations' ); ?></h1>
	<form class="rr-stats-filter" method="get"><input type="hidden" name="page" value="rr-statistics"><label><?php esc_html_e( 'Report date', 'restaurant-reservations' ); ?> <input type="date" name="date" value="<?php echo esc_attr( $date ); ?>"></label><?php submit_button( __( 'Update', 'restaurant-reservations' ), 'secondary', '', false ); ?></form>
	<nav class="rr-stats-tabs" aria-label="<?php esc_attr_e( 'Statistics periods', 'restaurant-reservations' ); ?>"><a href="#rr-daily"><?php esc_html_e( 'Daily', 'restaurant-reservations' ); ?></a><a href="#rr-weekly"><?php esc_html_e( 'Weekly', 'restaurant-reservations' ); ?></a><a href="#rr-monthly"><?php esc_html_e( 'Monthly', 'restaurant-reservations' ); ?></a></nav>
	<div class="rr-stat-cards">
		<section class="rr-stat-card" id="rr-daily"><h2><?php esc_html_e( 'Daily', 'restaurant-reservations' ); ?></h2><p class="rr-stat-date"><?php echo esc_html( wp_date( get_option( 'date_format' ), $timestamp ) ); ?></p><strong><?php echo absint( $daily['total_reservations'] ); ?></strong><span><?php esc_html_e( 'Reservations', 'restaurant-reservations' ); ?></span><strong><?php echo absint( $daily['total_guests'] ); ?></strong><span><?php esc_html_e( 'Guests', 'restaurant-reservations' ); ?></span></section>
		<section class="rr-stat-card" id="rr-weekly"><h2><?php esc_html_e( 'Weekly', 'restaurant-reservations' ); ?></h2><strong><?php echo absint( $weekly['total_reservations'] ); ?></strong><span><?php esc_html_e( 'Reservations', 'restaurant-reservations' ); ?></span><strong><?php echo absint( $weekly['total_guests'] ); ?></strong><span><?php esc_html_e( 'Guests', 'restaurant-reservations' ); ?></span><ol class="rr-week-breakdown"><?php for ( $i = 0; $i < 7; $i++ ) : $day = $week_start->format( 'Y-m-d' ); $day_stats = RRDatabase::get_daily_stats( $day ); ?><li><span><?php echo esc_html( wp_date( 'D j', strtotime( $day ) ) ); ?></span><b><?php echo absint( $day_stats['total_reservations'] ); ?></b></li><?php $week_start->modify( '+1 day' ); endfor; ?></ol></section>
		<section class="rr-stat-card" id="rr-monthly"><h2><?php esc_html_e( 'Monthly', 'restaurant-reservations' ); ?></h2><p class="rr-stat-date"><?php echo esc_html( wp_date( 'F Y', $timestamp ) ); ?></p><strong><?php echo absint( $monthly['total_reservations'] ); ?></strong><span><?php esc_html_e( 'Reservations', 'restaurant-reservations' ); ?></span><strong><?php echo absint( $monthly['total_guests'] ); ?></strong><span><?php esc_html_e( 'Guests', 'restaurant-reservations' ); ?></span><p><?php echo esc_html( sprintf( __( '%1$d confirmed, %2$d cancelled', 'restaurant-reservations' ), $monthly['confirmed'], $monthly['cancelled'] ) ); ?></p></section>
	</div>
	<?php $export_url = wp_nonce_url( add_query_arg( array( 'action' => 'rr_export_stats', 'start' => gmdate( 'Y-m-01', $timestamp ), 'end' => gmdate( 'Y-m-t', $timestamp ) ), admin_url( 'admin-post.php' ) ), 'rr_export_stats' ); ?><p><a class="button button-primary" href="<?php echo esc_url( $export_url ); ?>"><?php esc_html_e( 'Export CSV', 'restaurant-reservations' ); ?></a></p>
</div>

